config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  resources :plans, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :events, except: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :plan
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :tel, allow_blank: true, format: { with: VALID_PHONE_REGEX }
  validate :end_time_is_after_the_start_time
  
  def end_time_is_after_the_start_time
    unless end_time.nil? || start_time.nil? then
      if end_time < start_time
        errors.add(:end_time, "開始時間より後の時間にすることはできません。")
      end
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  validates :destination, presence: true, length: { maximum: 20 }
  validate :return_date_is_after_the_return_date
  
  
  def return_date_is_after_the_return_date
    if return_date < departure_date
      errors.add(:return_date, "出発日より前の日付にすることはできません。")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :plans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def new
    @event = Event.new
    @plan = Plan.find(params[:plan_id])
  end

  def create
    @plan = Plan.find(params[:plan_id])
    @event = @plan.events.build(event_params)
    if @event.save
      flash[:success] = '新たなイベントを登録しました。'
      redirect_to plan_path(@plan)
    else
     @events = @plan.events.order(id: :desc).page(params[:page])
      flash.now[:danger] = '新たなイベントの登録に失敗しました。'
      render 'events/new'
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = 'イベントは正常に更新されました'
      redirect_to plan_event_url
    else
      flash.now[:danger] = 'イベントは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to plan_path(@plan)
    flash[:success] = '旅行の計画を削除しました。'
  end
  
  private

  def event_params
    params.require(:event).permit(:title, :date, :start_time, :end_time, :tel, :url, :address, :currency, :budget, :memo)
  end
  
  def correct_user
    @event = Event.find(params[:id])
    @plan = current_user.plans.find(params[:plan_id])
    unless @plan
      redirect_to root_url
    end
  end


  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def new
    @plan = Plan.new
  end

  def create
    @plan = current_user.plans.build(plan_params)
    if @plan.save
      flash[:success] = '新たな旅行を登録しました。'
      redirect_to root_url
    else
      @plans = current_user.plans.order(id: :desc).page(params[:page])
      flash.now[:danger] = '新たな旅行の登録に失敗しました。'
      render 'plans/new'
    end
  end
  
  def show
    travel_period
    out_of_period
  end
  
  def edit
    
  end

  def update
    if @plan.update(plan_params)
      flash[:success] = 'イベントは正常に更新されました'
      redirect_to @plan
    else
      flash.now[:danger] = 'イベントは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @plan.destroy
    flash[:success] = '旅行の計画を削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def plan_params
    params.require(:plan).permit(:destination, :departure_date, :return_date)
  end
  
  def correct_user
    @plan = current_user.plans.find_by(id: params[:id])
    unless @plan
      redirect_to root_url
    end
  end

  def travel_period
    @departure = @plan.departure_date
    @return = @plan.return_date
    @travel_period = (@return - @departure).to_i
    @date = []
    while @departure <= @return do
      @date.push(@departure)
      @departure += 1
    end
  end
  
  def out_of_period
    @events = @plan.events.order(start_time: :asc).page(params[:page])
    @out_date = []
    @events.each do |event| 
      if event.date < @plan.departure_date || event.date > @plan.return_date
        @out_date.push(event.date)
      end
    end
    @out_date_uniq = @out_date.uniq
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @plans = current_user.plans.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      email = user_params[:email].downcase
      @user = User.find_by(email: email)
      session[:user_id] = @user.id
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/events/_from.html.erb
<% @departure = @plan.departure_date %>
<%  @return = @plan.return_date %>
<%  @travel_period = (@return - @departure).to_i %>
<%  @dates = [] %>
<%  while @departure <= @return do %>
   <% @dates.push(@departure) %>
   <% @departure += 1 %>
<%  end %>
  
<% @currency = ["¥","$","€","£"] %>

<div class="row">
  <div class="col-sm-4 offset-sm-4">
    <%= form_with(model: [@plan, @event], local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form_group mb-2">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title, class: 'form-control', :required => true %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :date, '日付' %>
      <%= f.select :date, @dates, {}, class: 'form-control', :required => true %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :start_time, '開始時間' %>
      <%= f.time_field :start_time, class: 'form-control' %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :end_time, '終了時間' %>
      <%= f.time_field :end_time, class: 'form-control' %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :url, 'URL' %>
      <%= f.text_field :url, class: 'form-control' %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :tel, '電話番号(ハイフンなし)' %>
      <%= f.telephone_field :tel, class: 'form-control' %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :address, '住所' %>
      <%= f.text_field :address, class: 'form-control' %>
      </div>
      <div class="form_group mb-2">
      <%= f.label :budget, '金額' %>
        <div class="row">
          <%= f.select :currency, @currency, {selected: "¥"}, class: 'form-control col-sm-2 ml-3', :required => true %>
          <%= f.text_field :budget, class: 'form-control col-sm-9', :value => number_with_precision(f.object.budget, precision: 2, strip_insignificant_zeros: true) %>
        </div>
      </div>
      <div class="form_group mb-2">
      <%= f.label :memo, 'メモ' %>
      <%= f.text_area :memo, class: 'form-control' %>
      </div>
      <%= f.submit '登録' %>
    <% end %>
    <p class="mt-3"><%= link_to 'スケジュールに戻る', plan_path(@plan), class: "text-danger" %></p>
  </div>
</div>

app/views/events/edit.html.erb
<h1 class="text-center">イベントの編集</h1>

<%= render 'from' %>

app/views/events/new.html.erb
<h1 class="text-center">イベント作成</h1>

<%= render 'from' %>

app/views/events/show.html.erb
<div class="offset-sm-4 col-sm-4">
  <h1 class="text-center"><%= @event.title %>の詳細</h1>
  
  <table class="table table-striped">
    <tr>
      <th style="width:40%">日付</th>
      <td style="width:60%"><%= @event.date.strftime("%Y年%m月%d日") %></td>
    </tr>
    <tr>
      <th>開始時間</th>
      <td>
        <% unless @event.start_time.nil? then %>
          <%= @event.start_time.strftime('%H:%M')  %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>終了時間</th>
      <td>
        <% unless @event.end_time.nil? then %>
          <%= @event.end_time.strftime('%H:%M')  %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>TEL</th>
      <td><%= link_to(@event.tel, "tel:#{@event.tel}") %></td>
    </tr>
    <tr>
      <th>URL</th>
      <td><%= link_to(@event.url, "#{@event.url}", target: :_blank) %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= link_to(@event.address, "https://www.google.com/maps/search/?api=1&query=#{@event.address}", target: :_blank) %></td>
    </tr>
    <tr>
      <th>金額</th>
      <td>
        <% unless @event.budget.nil? then %>
        <%= number_to_currency(@event.budget,unit:"#{@event.currency}",strip_insignificant_zeros:true) %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>メモ</th>
      <td><%= @event.memo %></td>
    </tr>
  </table>
  <%= link_to "編集", edit_plan_event_path, class: 'btn btn-secondary' %>
  <%= link_to "削除", plan_event_path(@plan, @event), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' %>
  <p class="mt-2"><%= link_to 'スケジュールに戻る', plan_path(@event.plan.id), class: "text-danger" %></p>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">TripBooks</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '新しい旅行の計画', new_plan_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TrpBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with(model: @plan, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form_group mb-3">
  <%= f.label :destination, '行き先' %>
  <%= f.text_field :destination, class: 'form-control', :required => true %>
  </div>
  <div class="form_group mb-3">
  <%= f.label :departure_date, '出発日' %>
  <%= f.date_field :departure_date, class: 'form-control', :required => true %>
  </div>
  <div class="form_group mb-3">
  <%= f.label :return_date, '帰着日' %>
  <%= f.date_field :return_date, class: 'form-control', :required => true %>
  </div>
  <%= f.submit '登録' %>
<% end %>

app/views/plans/_plans.html.erb
<div class="row">
  <% plans.each do |plan| %>
    <div class="col-md-3 mb-5 ">
      <div class="card" style="max-width: 18rem;">
        <div class="card_body text-center">
          <%= link_to plan, class: "text-dark" do %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light"><h4><%= plan.destination %></h4></li>
            <li class="list-group-item "><%= plan.departure_date%> ~ <%= plan.return_date%></li>
          </ul>
          <% end %>
        </div>
      </diV>
    </div>
  <% end %>
  <%= paginate plans %>
</div>

app/views/plans/_timetable.html.erb
<table class="table table-bordered bg-white">
  <tr class="position-relative">
    <td style="width:30%" class="text-center py-1">
      <% unless event.start_time.nil? then %>
        <%= event.start_time.strftime('%H:%M')  %>
      <% end %>
    </td>
    <td rowspan="2" class="align-middle">
      <a class="stretched-link"><%= link_to(event.title,plan_event_path(@plan,event.id)) %></a>
    </td>
  </tr>
  <tr class="position-relative">
    <td class="text-center py-1">
      <% unless event.end_time.nil? then %>
        <%= event.end_time.strftime('%H:%M')  %>
      <% end %>
    </td>
  </tr>
</table>

app/views/plans/create.html.erb
<h1>Plans#create</h1>
<p>Find me in app/views/plans/create.html.erb</p>

app/views/plans/destroy.html.erb
<h1>Plans#destroy</h1>
<p>Find me in app/views/plans/destroy.html.erb</p>

app/views/plans/edit.html.erb
<div class="offset-sm-4 col-sm-4">
  <h1 class="text-center">旅程の編集</h1>
  <%= render 'form' %>
  <p class="mt-3"><%= link_to "削除", plan_path(@plan), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
  <p class="mt-3"><%= link_to 'スケジュールに戻る', plan_path, class: "text-danger" %></p>
</div>

app/views/plans/new.html.erb
<div class="offset-sm-4 col-sm-4">
  <h1 class="text-center">新たな旅行計画</h1>
  <%= render 'form' %>
  <p class="mt-3"><%= link_to '一覧に戻る', root_path, class: "text-danger" %></p>
</div>

app/views/plans/show.html.erb
<h1 class="text-center"><%= @plan.destination %></h1>
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <ul class="sticky-top">
        <li class="list-group-item"><%= link_to "新規イベントの作成", new_plan_event_path(@plan) %></li>
        <li class="list-group-item"><%= link_to "旅行先・日程の編集", edit_plan_path %></li>
        <li class="list-group-item"><%= link_to "一覧へ戻る", root_url, class: "text-danger" %></li>
      </ul>
    </div>
    <div class="offset-sm-1 col-sm-4 mb-3">
      <div class="border bg-secondary" style="padding:20px 30px;">
        <% @date.each do |date| %>
          <div class="border border-secondary bg-light" style="padding: 10px 20px">
          <h5><%= date.strftime("%Y年%m月%d日") %></h5>
          <% @events.each do |event| %>
            <% if event.date == date %>
              <%= render 'timetable', { event: event } %>
            <% end %>
          <% end %>
          </div>
        <% end %>
      </div>
      <% unless @out_date_uniq.empty? then %>
        <h3 class="text-danger text-center mt-3">旅行期間外</h3>
        <div class="border bg-secondary" style="padding:20px 30px;">
          <% @out_date_uniq.sort.each do |date| %>
            <div class="border border-secondary bg-light" style="padding: 10px 20px">
              <h5><%= date.strftime("%Y年%m月%d日") %></h5>
              <% @events.each do |event| %>
                <% if event.date == date %>
                  <%= render 'timetable', { event: event } %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <% if @plans.any? %>
    <%= render 'plans/plans', plans: @plans %>
  <% else %>
    <div class="center jumbotron">
    <div class="text-center">
      <h1 class="mb-3">さっそく旅行の計画を立ててみましょう</h1>
      <%= link_to '新しい旅行の計画', new_plan_path, class: 'btn btn-lg btn-primary mr-5' %>
    </div>
  </div>
  <% end %>
      
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1 class="mb-3">Welcome to the TripBooks</h1>
      <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary mr-5' %>
      <%= link_to 'サインアップ', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control', :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control', :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation', :required => true %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'サインアップ', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>